version: '3.8'

services:
  nginx:
    container_name: bitovki-nginx
    image: "nginx:stable-alpine"
    ports:
      - 8000:443
    environment:
      - VIRTUAL_HOST=localhost
    volumes:
      - ./configs/nginx_prod.conf/:/etc/nginx/conf.d/default.conf:ro
      - /etc/ssl/certs:/etc/ssl/certs
      - /var/www/httpd-cert/www-root:/var/www/httpd-cert/www-root
      - ./src:/var/www/laravel
    networks:
      - backend

  nodejs:
    container_name: bitovki-nodejs
    environment:
      - PORT=5174
    build:
      context: dockerfiles
      dockerfile: nodejs.Dockerfile
    ports:
      - 5174:5174
    volumes:
      - ./src:/var/www/laravel
      - /etc/ssl/certs:/etc/ssl/certs
      - /var/www/httpd-cert/www-root:/var/www/httpd-cert/www-root
    networks:
      - backend

  php:
    container_name: bitovki-php
    build:
      context: dockerfiles
      dockerfile: php.Dockerfile
    volumes:
      - ./src:/var/www/laravel
      - ./configs/php.ini/:/usr/local/etc/php/conf.d/custom.ini
    networks:
      - backend

  mysql:
    container_name: bitovki-mysql
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    ports:
      - "3300:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
    networks:
      - backend

  phpmyadmin:
    container_name: bitovki-pma
    image: phpmyadmin:5.2
    ports:
      - 81:80
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      PMA_PORT: 3306
      UPLOAD_LIMIT: 64M
    networks:
      - backend

  # вспомогательные контейнеры
  composer:
    container_name: bitovki-composer
    build:
      context: dockerfiles
      dockerfile: composer.Dockerfile
    volumes:
      - ./src:/var/www/laravel
    networks:
      - backend

  artisan:
    container_name: bitovki-artisan
    build:
      context: dockerfiles
      dockerfile: php.Dockerfile
    volumes:
      - ./src:/var/www/laravel
    entrypoint: [ "php", "/var/www/laravel/artisan" ]
    networks:
      - backend

networks:
  backend:
    driver: bridge
